# Generated by Django 4.1 on 2022-08-10 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peso', '0002_delete_commento'),
    ]

    operations = [
        migrations.AddField(
            model_name='peso',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peso',
            name='date',
            field=models.DateField(),
        ),
    ]
