# Generated by Django 4.1 on 2022-08-22 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peso", "0003_peso_owner_alter_peso_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peso",
            name="peso",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
