# Generated by Django 4.1 on 2022-08-10 10:12

from django.db import migrations, models
import django.db.models.deletion
import pasto.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.PositiveIntegerField()),
                ('descrizione', models.TextField(max_length=1024)),
                ('foto', models.ImageField(upload_to=pasto.models.user_directory_path)),
                ('tipo', models.CharField(choices=[(1, 'colazione'), (2, 'pranzo'), (3, 'snack'), (4, 'cena')], max_length=1)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commento', models.TextField(max_length=512)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('pasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasto.pasto')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pasto.commento')),
            ],
        ),
    ]
