# Generated by Django 4.1 on 2022-08-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasto', '0002_commento_owner_pasto_created_pasto_date_pasto_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasto',
            name='foto',
        ),
    ]
