# Generated by Django 4.1 on 2022-08-10 11:59

from django.db import migrations, models
import pasto.models


class Migration(migrations.Migration):

    dependencies = [
        ('pasto', '0003_remove_pasto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasto',
            name='foto',
            field=models.ImageField(default=1, upload_to=pasto.models.user_directory_path),
            preserve_default=False,
        ),
    ]
