# Generated by Django 4.1 on 2022-08-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasto', '0004_pasto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasto',
            name='date',
            field=models.DateField(),
        ),
    ]
