# Generated by Django 4.1 on 2022-08-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasto', '0005_alter_pasto_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasto',
            name='tipo',
            field=models.CharField(blank=True, choices=[(1, 'colazione'), (2, 'pranzo'), (3, 'snack'), (4, 'cena')], max_length=1, null=True),
        ),
    ]
