# Generated by Django 4.1 on 2022-08-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasto', '0011_likepasto_likecommento'),
    ]

    operations = [
        migrations.AddField(
            model_name='commento',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
