# Generated by Django 4.1 on 2022-08-14 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pasto', '0012_commento_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commento',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='commento',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='likecommento',
            name='like',
        ),
        migrations.RemoveField(
            model_name='likepasto',
            name='like',
        ),
        migrations.RemoveField(
            model_name='pasto',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='pasto',
            name='likes',
        ),
        migrations.CreateModel(
            name='DisLikePasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pasto.pasto')),
            ],
        ),
        migrations.CreateModel(
            name='DisLikeCommento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pasto.commento')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
