# Generated by Django 4.1 on 2022-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasto', '0013_remove_commento_dislikes_remove_commento_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislikepasto',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dislikepasto',
            name='pasto',
        ),
        migrations.AddField(
            model_name='commento',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='DisLikeCommento',
        ),
        migrations.DeleteModel(
            name='DisLikePasto',
        ),
    ]
